### PR TITLE
Added alarm clock and rock paper scissors game

### PR DESCRIPTION
**Pull request by mansijain014**

### CODE REVIEW

**Review by G1Joshi — COMMENTED** [review]
@mansijain014 add all these files into ```Clock/```directory

**Comment by mansijain014** [comment]
> @mansijain014 add all these files into `Clock/`directory

Okayy I'll do it.

**Review by G1Joshi — CHANGES_REQUESTED** [review]
@mansijain014 add files in appropriate directory

**Comment by mansijain014** [comment]
> @mansijain014 add files in appropriate directory

I did it already..you've merged it also
Screenshot 2020-10-08 170549

**Pull request closed without merging**
