### PR TITLE
CountdownClock

### PR DESCRIPTION
**Pull request by prikshitsetia**
I have made a countdown clock and timer where the user has to enter the time in seconds and the countdown starts from that number of seconds until zero.

### CODE REVIEW

**Comment by prikshitsetia** [comment]
Tic Toe game has also been added which is in java and also GUI based game and it can be played between a user and computer

**Review by G1Joshi — CHANGES_REQUESTED** [review]
@prikshitsetia add your files inside your ```username``` folder

**Comment by prikshitsetia** [comment]
I have added the files inside my username folder

**Review by G1Joshi — APPROVED** [review]

**Comment by G1Joshi** [comment]
Welcome to the world of C0D1NG 🚀

**Comment by prikshitsetia** [comment]
hey, I just came to know about some changes that the maintainer has to do on their part for a valid PR.

please visit this link and check:
[https://hacktoberfest.digitalocean.com/hacktoberfest-update](url)

**Comment by prikshitsetia** [comment]
> Welcome to the world of C0D1NG 🚀

Thankyou

**Pull request merged**
