### PR TITLE
Todo App

### PR DESCRIPTION
**Pull request by devankit01**

### CODE REVIEW

**Comment by G1Joshi** [comment]
Great @devankit01 🚀
Please put all your source codes into
Calculator/Username/
Calendar/Username/
Todo/Username/

**Review by G1Joshi — CHANGES_REQUESTED** [review]
Location
```Calculator/YourUsername/```
```Calendar/YourUsername/```
```To-Do/YourUsername/```

**Comment by devankit01** [comment]
> Great @devankit01 🚀
> Please put all your source codes into specified location.

Thanks I will do that

**Comment by devankit01** [comment]
I have done changes by forking but unable to create a pull request.

**Review by G1Joshi — APPROVED** [review]

**Comment by devankit01** [comment]
Thank You and I am also there 😊😉

**Comment by devankit01** [comment]
Hiii , I think you haven't mentioned hacktoberfest tag in my PRs . Please tell me I have to add it or I have done any mistake.

**Pull request merged**
